name: Publish examples

on:
  workflow_run:
    workflows: ['Dummy1']
    branches: ['jancizmar/TG-428-example-publishing-commit-message']
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.commits[0].message }}
