name: Dummy 2

on:
  workflow_run:
    workflows: ['Dummy1']
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git show -s --format=%s
